### ISSUE TITLE
Private SSH key

### ISSUE THREAD

**Issue by lukaspj** [SorenA/light-hosting-kube#1]
I had to add `private_key = file(var.ssh_private_key)` to _terraform/modules/provider/hcloud/main.tf_ in the remote_exec blocks.

Am I doing anything wrong here?

**Comment by SorenA** [comment]
Hi Lukas!

I think the reason that the line is not in the provider source, is that my SSH key is registered in my ssh agent, so it is configured already, that's one way to do it.

Another way is reading the contents from file like you're doing it.
I believe i tried doing it like that as well first, but ran into issues with due to the SSH keys being encrypted.

**Comment by SorenA** [comment]
I've added some documentation regarding SSH keys to the README.

Thanks for bringing it up!
